---
title: "Satnogs Analysis"
author: "Ada Lazuli"
date: '2022-10-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(ggplot2)
library(dplyr)
```

# Data Loading

`{bash, engine.opts='-l'}
cat ../data/bad.csv.part* >> ../data/bad.csv
cat ../data/good.csv.part* >> ../data/good.csv
`

```{r}
bad <- read.csv("../data/bad.csv", nrows = 200)
bad$Signal <- FALSE
good <- read.csv("../data/good.csv", nrows = 200)
good$Signal <- TRUE
glimpse(good)
df <- rbind(bad, good)
```

# Analysis

## Frequency

```{r}
label_band <- function(freq) {
if ((freq <= 300) & (freq >= 30))
return("VHF")
if ((freq <= 1000 ) & (freq > 30))
return("UHF")
if ((freq <= 2000) & (freq > 1000))
return("L-Band")
if ((freq <= 4000) & (freq > 2000))
return("S-Band")
return("Unk")
}
df <- df %>% mutate(Frequency = as.numeric(gsub(r"[\D]", "", Frequency))) %>%
  mutate(Frequency = Frequency/1000000)
df$Band <- sapply(df$Frequency, FUN = label_band)
counts <- df %>% group_by(Band) %>% count()

```

### UHF

```{r}
ggplot(counts, aes(x = Band, y = n, color = Band, fill = Band)) + geom_col() + labs(title = "Frequency Bands", x ="Band", y = "Counts")
ggplot(df %>% filter(Band == "UHF"), aes(x = Frequency)) + geom_histogram(bins = 1000) +  labs(title = "Histogram of UHF Frequencies", x ="Frequency", y = "Counts")
ggplot(df %>% filter(Band == "UHF"), aes(x = Frequency, color = Signal, fill = Signal)) + geom_histogram(bins = 1000, alpha = 0.4) +  labs(title = "Histogram of UHF Frequencies", x ="Frequency", y = "Counts")
```

### VHF

```{r}
ggplot(df %>% filter(Band == "VHF"), aes(x = Frequency)) + geom_histogram(bins = 1000) +  labs(title = "Histogram of VHF Frequencies", x ="Frequency", y = "Counts")
ggplot(df %>% filter(Band == "VHF"), aes(x = Frequency, color = Signal, fill = Signal)) + geom_histogram(bins = 1000) +  labs(title = "Histogram of VHF Frequencies", x ="Frequency", y = "Counts")
```


### L-Band

```{r}
ggplot(df %>% filter(Band == "L-Band"), aes(x = Frequency)) + geom_histogram(bins = 1000) +  labs(title = "Histogram of L-Band Frequencies", x ="Frequency", y = "Counts")
ggplot(df %>% filter(Band == "L-Band"), aes(x = Frequency, color = Signal, fill = Signal)) + geom_histogram(bins = 1000) +  labs(title = "Histogram of L-Band Frequencies", x ="Frequency", y = "Counts")
```


### S-Band

```{r}
ggplot(df %>% filter(Band == "S-Band"), aes(x = Frequency)) + geom_histogram(bins = 1000) +  labs(title = "Histogram of S-Band Frequencies", x ="Frequency", y = "Counts")
ggplot(df %>% filter(Band == "S-Band"), aes(x = Frequency, color = Signal, fill = Signal)) + geom_histogram(bins = 1000) +  labs(title = "Histogram of S-Band Frequencies", x ="Frequency", y = "Counts")
```


